deployment:
  imageURL: 090808669085.dkr.ecr.us-east-1.amazonaws.com/expense/frontend
  version: IMAGE_VERSION
hpa:
  utilization: 5
tgb:
  arn: arn:aws:elasticloadbalancing:us-east-1:090808669085:targetgroup/expense-dev-frontend/4f57cf1c96b75722